# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 21:31
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('imagen1', models.ImageField(upload_to=b'')),
                ('fecha', models.CharField(max_length=30)),
                ('desarrollo', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaAs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historia', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Junta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Miembros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to=b'')),
                ('cargos', models.CharField(choices=[(b'Presidenta', b'Presidenta'), (b'Vicepresidenta', b'Vicepresidenta'), (b'Presidenta Honoraria', b'Presidenta Honoraria'), (b'Secretaria', b'Secretaria'), (b'Vicesecretaria', b'Vicesecretaria'), (b'Tesorera', b'Tesorera'), (b'Vicetesorera', b'Vicetesorera'), (b'Vocal', b'Vocal'), (b'Vocal', b'Vocal')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('cuerpo', models.TextField(max_length=500)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=50)),
                ('historia', models.TextField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='junta',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuadalupeApp.Miembros'),
        ),
    ]
