# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-25 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GuadalupeApp', '0002_auto_20170124_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembros',
            name='foto',
        ),
    ]
