# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-25 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuadalupeApp', '0003_remove_miembros_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaVirgen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desarrollo', models.TextField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='cultos',
            old_name='imagen1',
            new_name='imagen',
        ),
        migrations.AddField(
            model_name='cultos',
            name='culto',
            field=models.CharField(choices=[(b'Novena', b'Novena'), (b'Serenata', b'Serenata'), (b'Verbena', b'Verbena'), (b'Presentacion', b'Presentacion a la Virgen')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
