# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-25 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuadalupeApp', '0004_auto_20170125_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultos',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='cultos',
            name='fecha',
            field=models.CharField(max_length=50),
        ),
    ]
