# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-26 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuadalupeApp', '0006_auto_20170126_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tesoreria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='historiaas',
            name='historia',
            field=models.TextField(max_length=1000),
        ),
    ]
