# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-26 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuadalupeApp', '0007_auto_20170126_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='portada',
            field=models.ImageField(default=0, upload_to=b''),
            preserve_default=False,
        ),
    ]
