# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-26 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuadalupeApp', '0008_noticia_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='intro',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
