# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-29 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GuadalupeApp', '0010_auto_20170129_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimagen',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='GuadalupeApp.Album'),
        ),
        migrations.AlterField(
            model_name='albumimagen',
            name='imagen',
            field=models.ImageField(upload_to=b''),
        ),
    ]
