# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuadalupeApp', '0012_auto_20170129_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='cuerpo',
            field=models.TextField(max_length=1500),
        ),
    ]
