# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-02 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuadalupeApp', '0013_auto_20170201_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumimagen',
            name='titulo',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cultos',
            name='desarrollo2',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historiaas',
            name='historia2',
            field=models.TextField(default=0, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historiaas',
            name='historia3',
            field=models.TextField(default=0, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historiaas',
            name='imagen1',
            field=models.ImageField(default=0, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historiaas',
            name='imagen2',
            field=models.ImageField(default=0, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historiaas',
            name='imagen3',
            field=models.ImageField(default=0, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historiavirgen',
            name='desarrollo2',
            field=models.TextField(default=0, max_length=2500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historiavirgen',
            name='desarrollo3',
            field=models.TextField(default=0, max_length=2500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historiavirgen',
            name='desarrollo4',
            field=models.TextField(default=0, max_length=2500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historiavirgen',
            name='imagen1',
            field=models.ImageField(default=0, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historiavirgen',
            name='imagen2',
            field=models.ImageField(default=0, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historiavirgen',
            name='imagen3',
            field=models.ImageField(default=0, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='cuerpo2',
            field=models.TextField(default=0, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='cuerpo3',
            field=models.TextField(default=0, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen1',
            field=models.ImageField(default=0, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen2',
            field=models.ImageField(default=0, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sede',
            name='imagen',
            field=models.ImageField(default=0, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sede',
            name='imagen2',
            field=models.ImageField(default=0, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sede',
            name='imagen3',
            field=models.ImageField(default=0, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='titulo',
            field=models.CharField(choices=[(b'Actividades', b'Actividades'), (b'Ntra. Sra. de Guadalupe', b'Ntra. Sra. de Guadalupe'), (b'Viajes', b'Viajes'), (b'Encuentros', b'Encuentros'), (b'Novena', b'Novena'), (b'Serenata', b'Serenata'), (b'Verbena', b'Verbena'), (b'Presentacion', b'Presentacion a la Virgen')], max_length=60),
        ),
        migrations.AlterField(
            model_name='cultos',
            name='desarrollo',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='cultos',
            name='fecha',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaas',
            name='historia',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='historiavirgen',
            name='desarrollo',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='miembros',
            name='cargos',
            field=models.CharField(choices=[(b'Presidenta', b'Presidenta'), (b'Vicepresidenta', b'Vicepresidenta'), (b'Presidenta Honoraria', b'Presidenta Honoraria'), (b'Secretaria', b'Secretaria'), (b'Vicesecretaria', b'Vicesecretaria'), (b'Tesorera', b'Tesorera'), (b'Vicetesorera', b'Vicetesorera'), (b'Vocal', b'Vocal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='intro',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sede',
            name='historia',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='sede',
            name='lugar',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tesoreria',
            name='texto',
            field=models.TextField(max_length=1000),
        ),
    ]
