# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-04 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuadalupeApp', '0014_auto_20170202_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultos',
            name='desarrollo3',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sede',
            name='historia2',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sede',
            name='historia3',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='titulo',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='miembros',
            name='cargos',
            field=models.CharField(choices=[(b'Consiliario', b'Consiliario'), (b'Presidenta', b'Presidenta'), (b'Vicepresidenta', b'Vicepresidenta'), (b'Presidenta Honoraria', b'Presidenta Honoraria'), (b'Secretaria', b'Secretaria'), (b'Vicesecretaria', b'Vicesecretaria'), (b'Tesorera', b'Tesorera'), (b'Vicetesorera', b'Vicetesorera'), (b'Vocal', b'Vocal')], max_length=20),
        ),
    ]
