# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-04 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuadalupeApp', '0015_auto_20170204_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumimagen',
            name='pie',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
