# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-04 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuadalupeApp', '0018_auto_20170204_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultos',
            name='desarrollo',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='cultos',
            name='desarrollo2',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='cultos',
            name='desarrollo3',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='historiaas',
            name='historia',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='historiaas',
            name='historia2',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='historiaas',
            name='historia3',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='historiavirgen',
            name='desarrollo',
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name='historiavirgen',
            name='desarrollo2',
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name='historiavirgen',
            name='desarrollo3',
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name='historiavirgen',
            name='desarrollo4',
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='cuerpo',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='cuerpo2',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='cuerpo3',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen1',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen2',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='portada',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='sede',
            name='historia',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='sede',
            name='historia2',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='sede',
            name='historia3',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='tesoreria',
            name='texto',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
