# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-04 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuadalupeApp', '0019_auto_20170204_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumEspecifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('owner', models.CharField(max_length=60)),
                ('portada', models.ImageField(blank=True, upload_to=b'')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='portada',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='albumimagen',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='albumimagen',
            name='pie',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='cultos',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='cultos',
            name='imagen2',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='historiavirgen',
            name='imagen1',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='historiavirgen',
            name='imagen2',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='historiavirgen',
            name='imagen3',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='sede',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='sede',
            name='imagen2',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='sede',
            name='imagen3',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
