# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-04 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GuadalupeApp', '0020_auto_20170204_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumespecifico',
            name='album',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='GuadalupeApp.Album'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='albumimagen',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='GuadalupeApp.AlbumEspecifico'),
        ),
    ]
